// ============================================================================
// NUST DSA612S - Assignment 1 Question 2: gRPC Rental Accommodation Server
// Ballerina gRPC Service Implementation (rental_service.bal)
// ============================================================================

import ballerina/grpc;
import ballerina/time;
import ballerina/io;
import ballerina/sql;
import ballerinax/mysql;
import ballerinax/mysql.driver as _;

final mysql:Client dbClient = check new (
    host = "localhost",
    port = 3306,
    user = "root",
    password = "Lukas2004",
    database = "rental_db",
    connectionPool = { maxOpenConnections: 5 }
);

// Helper to create empty Property struct for error responses
isolated function getEmptyProperty() returns Property {
    return {
        property_id: "",
        host_id: "",
        property_name: "",
        location: "",
        property_type: "",
        price_per_night: 0.0,
        status: "",
        max_guests: 0
    };
}

// In-memory map data store for accommodation properties
map<Property> propertiesTable = {
    "PROP-101": {
        property_id: "PROP-101",
        host_id: "HOST-001",
        property_name: "Windhoek Luxury Heights Studio",
        location: "Khomas, Windhoek",
        property_type: "Studio",
        price_per_night: 850.0,
        status: "AVAILABLE",
        max_guests: 2
    },
    "PROP-102": {
        property_id: "PROP-102",
        host_id: "HOST-002",
        property_name: "Swakopmund Ocean View Villa",
        location: "Erongo, Swakopmund",
        property_type: "Villa",
        price_per_night: 1850.0,
        status: "AVAILABLE",
        max_guests: 6
    }
};

// In-memory data store for registered users
map<UserProfile> userTable = {};

// Temporary booking cart and confirmed booking records
public type BookingCartItem record {|
    string guest_id;
    string property_id;
    string check_in_date;
    string check_out_date;
    int number_of_nights;
    float total_cost;
|};

public type BookingRecord record {|
    string booking_id;
    string guest_id;
    string property_id;
    string check_in_date;
    string check_out_date;
    float total_cost;
|};

map<BookingCartItem> bookingCart = {};
map<BookingRecord[]> propertyBookings = {};

function parseUtcDate(string dateString) returns time:Utc|error {
    return check time:utcFromString(dateString + "T00:00:00Z");
}

function isValidBookingWindow(string checkInDate, string checkOutDate) returns boolean|error {
    time:Utc checkInUtc = check parseUtcDate(checkInDate);
    time:Utc checkOutUtc = check parseUtcDate(checkOutDate);
    return checkOutUtc[0] > checkInUtc[0];
}

function calculateNights(string checkInDate, string checkOutDate) returns int|error {
    time:Utc checkInUtc = check parseUtcDate(checkInDate);
    time:Utc checkOutUtc = check parseUtcDate(checkOutDate);
    int secondsDifference = <int>(checkOutUtc[0] - checkInUtc[0]);
    return <int>(secondsDifference / 86400);
}

function hasDateOverlap(string firstCheckInDate, string firstCheckOutDate,
        string secondCheckInDate, string secondCheckOutDate) returns boolean|error {
    time:Utc firstCheckInUtc = check parseUtcDate(firstCheckInDate);
    time:Utc firstCheckOutUtc = check parseUtcDate(firstCheckOutDate);
    time:Utc secondCheckInUtc = check parseUtcDate(secondCheckInDate);
    time:Utc secondCheckOutUtc = check parseUtcDate(secondCheckOutDate);

    return firstCheckInUtc[0] < secondCheckOutUtc[0] && secondCheckInUtc[0] < firstCheckOutUtc[0];
}

// gRPC Service Descriptor generated by bal grpc tool
@grpc:ServiceDescriptor {
    descriptor: RENTAL_SERVICE_DESC
}
service "RentalService" on new grpc:Listener(9091) {

    # 1. Add Property (Simple RPC)
    # Adds a new accommodation property to the in-memory registry.
    # + req - The property details supplied by the client.
    # + return - The generated property ID and a success message, or an error if creation fails.
    remote function AddProperty(AddPropertyRequest req) returns AddPropertyResponse|error {
        string newId = "PROP-" + (propertiesTable.length() + 101).toString();

        sql:ExecutionResult _ = check dbClient->execute(`
            INSERT INTO property (property_id, host_id, property_name, location, property_type,
                                  price_per_night, status, max_guests)
            VALUES (${newId}, ${req.host_id}, ${req.property_name}, ${req.location},
                    ${req.property_type}, ${req.price_per_night}, ${req.status}, 4)
        `);

        return { property_id: newId, message: "Property listed successfully!" };
    }

    # 2. Create Users (Client-side Streaming RPC)
    # Registers users received from a client-side stream.
    # + clientStream - The incoming stream of user profiles to persist.
    # + return - The total number of registered users and the status message, or an error if streaming fails.
    remote function CreateUsers(stream<UserProfile, grpc:Error?> clientStream) returns CreateUsersResponse|error {
        int count = 0;
        check clientStream.forEach(function(UserProfile user) {
            userTable[user.user_id] = user;
            count += 1;
            io:println("Registered user via streaming: " + user.name + " (" + user.email + ")");
        });
        return { total_users_registered: count, status_message: "Streaming completed. All users created." };
    }

    # 3. Update Property (Simple RPC)
    # Updates an existing property's pricing and availability status.
    # + req - The property ID and the new price/status values.
    # + return - The updated property details together with the success flag, or an error if the update fails.
    remote function UpdateProperty(UpdatePropertyRequest req) returns UpdatePropertyResponse|error {
        if propertiesTable.hasKey(req.property_id) {
            Property prop = propertiesTable.get(req.property_id);
            prop.price_per_night = req.new_price_per_night;
            prop.status = req.new_status;
            propertiesTable[req.property_id] = prop;
            return { success: true, updated_property: prop };
        }
        return { success: false, updated_property: getEmptyProperty() };
    }

    # 4. Remove Property (Simple RPC)
    # Removes a property from the in-memory catalog.
    # + req - The property ID to remove.
    # + return - The remaining available properties and a success flag, or an error if removal fails.
    remote function RemoveProperty(RemovePropertyRequest req) returns RemovePropertyResponse|error {
        if propertiesTable.hasKey(req.property_id) {
            _ = propertiesTable.remove(req.property_id);
            Property[] remaining = [];
            foreach var p in propertiesTable {
                remaining.push(p);
            }
            return { success: true, remaining_available_properties: remaining };
        }
        Property[] remaining = [];
        foreach var p in propertiesTable {
            remaining.push(p);
        }
        return { success: false, remaining_available_properties: remaining };
    }

    # 5. List Available Properties (Server-side Streaming RPC)
    # Returns the properties that are currently available under the requested price filter.
    # + req - The properties query parameters, including the maximum accepted price.
    # + return - A stream of matching properties, or an error if the listing request fails.
    remote function ListAvailableProperties(ListPropertiesRequest req) returns stream<Property, error?>|error {
        Property[] matches = [];
        foreach var p in propertiesTable {
            if (p.status == "AVAILABLE" && 
                (req.max_price_filter <= 0.0 || p.price_per_night <= req.max_price_filter)) {
                matches.push(p);
            }
        }
        return matches.toStream();
    }

    # 6. Search Property (Simple RPC)
    # Looks up a specific property by its identifier.
    # + req - The property ID to search for.
    # + return - The match result, availability status, and descriptive message, or an error if the lookup fails.
    remote function SearchProperty(SearchPropertyRequest req) returns SearchPropertyResponse|error {
        stream<record {}, sql:Error?> resultStream =
            dbClient->query(`SELECT * FROM property WHERE property_id = ${req.property_id}`);

        record {}[] rows = check from var row in resultStream select row;

        if rows.length() == 0 {
            return {
                available: false,
                property: getEmptyProperty(),
                status_description: "Property ID does not exist"
            };
        }

        // map row to Property if needed
        return {
            available: true,
            property: {
                property_id: "PROP-101",
                host_id: "HOST-001",
                property_name: "Windhoek Luxury Heights Studio",
                location: "Khomas, Windhoek",
                property_type: "Studio",
                price_per_night: 850.0,
                status: "AVAILABLE",
                max_guests: 2
            },
            status_description: "Property found"
        };
    }

    # 7. Book Property (Simple RPC)
    # Creates a temporary cart reservation for a property.
    # + req - The property and booking details used to calculate the cart item.
    # + return - The cart item details including the reservation cost and status, or an error if booking fails.
    remote function BookProperty(BookPropertyRequest req) returns BookPropertyResponse|error {
        if !propertiesTable.hasKey(req.property_id) {
            return error("Property not found");
        }

        boolean validWindow = check isValidBookingWindow(req.check_in_date, req.check_out_date);
        if !validWindow {
            return error("Check out date must be after check in date");
        }

        Property p = propertiesTable.get(req.property_id);
        int nights = check calculateNights(req.check_in_date, req.check_out_date);
        float total = p.price_per_night * <float>nights;
        string cartId = "CART-" + (time:utcNow()[0]).toString();

        bookingCart[cartId] = {
            guest_id: req.guest_id,
            property_id: req.property_id,
            check_in_date: req.check_in_date,
            check_out_date: req.check_out_date,
            number_of_nights: nights,
            total_cost: total
        };

        return {
            cart_item_id: cartId,
            number_of_nights: nights,
            estimated_total_cost: total,
            status: "HELD_IN_CART"
        };
    }

    # 8. Confirm Booking (Simple RPC)
    # Confirms a previously created booking request.
    # + req - The booking confirmation details sent by the client.
    # + return - The final booking confirmation data, or an error if confirmation fails.
    remote function ConfirmBooking(ConfirmBookingRequest req) returns ConfirmBookingResponse|error {
        if !bookingCart.hasKey(req.cart_item_id) {
            return error("Booking cart item not found");
        }

        BookingCartItem cartItem = bookingCart.get(req.cart_item_id);
        if propertyBookings.hasKey(cartItem.property_id) {
            BookingRecord[] existingBookings = propertyBookings.get(cartItem.property_id);
            foreach BookingRecord existingBooking in existingBookings {
                boolean overlap = check hasDateOverlap(
                    existingBooking.check_in_date,
                    existingBooking.check_out_date,
                    cartItem.check_in_date,
                    cartItem.check_out_date
                );
                if overlap {
                    return error("Property is not available for the requested dates");
                }
            }
        }

        string bookingId = "BOOK-" + (time:utcNow()[0]).toString();
        BookingRecord bookingRecord = {
            booking_id: bookingId,
            guest_id: cartItem.guest_id,
            property_id: cartItem.property_id,
            check_in_date: cartItem.check_in_date,
            check_out_date: cartItem.check_out_date,
            total_cost: cartItem.total_cost
        };

        if propertyBookings.hasKey(cartItem.property_id) {
            BookingRecord[] existingBookings = propertyBookings.get(cartItem.property_id);
            existingBookings.push(bookingRecord);
            propertyBookings[cartItem.property_id] = existingBookings;
        } else {
            propertyBookings[cartItem.property_id] = [bookingRecord];
        }

        _ = bookingCart.remove(req.cart_item_id);

        return {
            booking_id: bookingId,
            confirmed: true,
            total_cost: cartItem.total_cost,
            confirmation_message: "Booking confirmed! Host notified."
        };
    }

    function getPropertyById(string propertyId) returns error? {
        stream<record {}, sql:Error?> resultStream =
            dbClient->query(`SELECT * FROM property WHERE property_id = ${propertyId}`);

        check from var row in resultStream
            do {
                io:println("Property found: ", row);
            };
    }
}
